database:
    driver: 'pdo_mysql'
    host: 'localhost'
    dbname: 'crilloil'
    port: ''
    user: 'root'
    password : 'root'
    charset: utf8
    defaultTableOptions: { collate: utf8_general_ci }
