root: /eccube/crilloil/html/
admin_dir: crilloil/
tpl: /eccube/crilloil/html/user_data/packages/default/
admin_tpl: /eccube/crilloil/html/user_data/packages/admin/
image_path: /eccube/crilloil/html/upload/save_image/
root_dir: /Applications/MAMP/htdocs/eccube/crilloil
root_urlpath: /eccube/crilloil/html
template_code: fandg
admin_route: crilloil
user_data_route: user_data
public_path: /html
public_path_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html
image_save_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html/upload/save_image
image_temp_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html/upload/temp_image
user_data_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html/user_data
block_default_realdir: /Applications/MAMP/htdocs/eccube/crilloil/src/Eccube/Resource/template/default/Block
block_realdir: /Applications/MAMP/htdocs/eccube/crilloil/app/template/fandg/Block
template_default_realdir: /Applications/MAMP/htdocs/eccube/crilloil/src/Eccube/Resource/template/default
template_default_html_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html/template/default
template_admin_realdir: /Applications/MAMP/htdocs/eccube/crilloil/src/Eccube/Resource/template/admin
template_admin_html_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html/template/admin
template_realdir: /Applications/MAMP/htdocs/eccube/crilloil/app/template/fandg
template_html_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html/template/fandg
template_temp_realdir: /Applications/MAMP/htdocs/eccube/crilloil/app/cache/eccube/template
csv_temp_realdir: /Applications/MAMP/htdocs/eccube/crilloil/app/cache/eccube/csv
plugin_realdir: /Applications/MAMP/htdocs/eccube/crilloil/app/Plugin
plugin_temp_realdir: /Applications/MAMP/htdocs/eccube/crilloil/app/cache/plugin
plugin_html_realdir: /Applications/MAMP/htdocs/eccube/crilloil/html/plugin
admin_urlpath: /eccube/crilloil/html/template/admin
front_urlpath: /eccube/crilloil/html/template/fandg
image_save_urlpath: /eccube/crilloil/html/upload/save_image
image_temp_urlpath: /eccube/crilloil/html/upload/temp_image
user_data_urlpath: /eccube/crilloil/html/user_data
plugin_urlpath: /eccube/crilloil/html/plugin
